---
#System
- name: Show battery parcent
  osx_defaults: domain=com.apple.menuextra.battery key=ShowPercent type=string value="YES"

# Trackpad
- name: Enable Tap to Click
  osx_defaults: domain=com.apple.AppleMultitouchTrackpad key=Clicking type=int value=1

# Keyboard
- name: Set InitialKeyRepeat speedy
  osx_defaults: key=InitialKeyRepeat type=int value=10

- name: Set KeyRepeat shortly
  osx_defaults: key=KeyRepeat type=int value=1

# Dock
- name: Dock autohide
  osx_defaults: domain=com.apple.dock key=autohide type=int value=1

- name: Disable Dock Animation
  osx_defaults: domain=com.apple.dock key=autohide-time-modifier type=float value=0

# Safari
- name: Enable safari debug menu
  osx_defaults:
    domain: com.apple.Safari
    key: IncludeInternalDebugMenu
    type: bool
    value: true
    state: present


# Mission Controll
- name: Disable Mission Controll auto switch
  osx_defaults: domain=com.apple.dock key=mru-spaces type=bool value=false

# Finder
- name: Open New finder window by HOME directory 
  osx_defaults: domain=com.apple.finder key=NewWindowTargetPath type=string value="file://${HOME}"

- name: Enable QuickLook text selection
  osx_defaults: domain=com.apple.finder key=QLEnableTextSelection type=bool value=true

  #  notify:
  #    command: 'killall Finder'
